# Generated by Django 5.0.14 on 2025-12-18 19:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment_centers', '0001_initial'),
        ('configurations', '0002_delete_systemconfiguration'),
        ('occupations', '0004_occupationpaper'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(help_text='Unique registration number for the candidate', max_length=50, unique=True, verbose_name='Registration Number')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('nationality', models.CharField(default='Uganda', max_length=100)),
                ('is_refugee', models.BooleanField(default=False, verbose_name='Is Refugee?')),
                ('refugee_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Refugee Identification Number')),
                ('contact', models.CharField(max_length=20, verbose_name='Contact Number')),
                ('has_disability', models.BooleanField(default=False, verbose_name='Has Disability?')),
                ('disability_specification', models.TextField(blank=True, help_text='Provide specific details about the disability', verbose_name='Disability Specification')),
                ('entry_year', models.IntegerField(verbose_name='Entry Year')),
                ('intake', models.CharField(choices=[('M', 'March'), ('A', 'August')], max_length=1, verbose_name='Intake')),
                ('registration_category', models.CharField(choices=[('modular', 'Modular'), ('formal', 'Formal'), ('workers_pas', "Worker's PAS")], max_length=20, verbose_name='Registration Category')),
                ('preferred_assessment_language', models.CharField(default='English', max_length=50, verbose_name='Preferred Assessment Language')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Training Start Date')),
                ('finish_date', models.DateField(blank=True, null=True, verbose_name='Training Finish Date')),
                ('assessment_date', models.DateField(blank=True, null=True, verbose_name='Assessment Date')),
                ('enrollment_level', models.CharField(blank=True, help_text='Current level of enrollment', max_length=100, verbose_name='Enrollment Level')),
                ('reg_number', models.CharField(blank=True, max_length=100, verbose_name='Legacy Registration Number')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('completed', 'Completed')], default='active', max_length=20, verbose_name='Account Status')),
                ('block_portal_results', models.BooleanField(default=False, help_text='If checked, this candidate cannot view results in the portal', verbose_name='Block Portal Results')),
                ('fees_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Outstanding Fees Balance')),
                ('modular_module_count', models.IntegerField(blank=True, help_text='For Modular candidates, specify number of modules (1 or 2)', null=True, verbose_name='Modular Module Count')),
                ('modular_billing_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Modular Billing Amount')),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='candidates/photos/', verbose_name='Passport Photo')),
                ('passport_photo_with_regno', models.ImageField(blank=True, null=True, upload_to='candidates/photos_with_regno/', verbose_name='Passport Photo with Registration Number')),
                ('identification_document', models.FileField(blank=True, help_text='National ID, Birth Certificate, or other identification (PNG, JPG, PDF max 10MB)', null=True, upload_to='candidates/documents/identification/', verbose_name='Identification Document')),
                ('qualification_document', models.FileField(blank=True, help_text='Relevant qualifications for Full Occupation candidates (PNG, JPG, or PDF max 10MB)', null=True, upload_to='candidates/documents/qualifications/', verbose_name='Qualification Document')),
                ('verification_status', models.CharField(choices=[('pending_verification', 'Pending Verification'), ('verified', 'Verified'), ('declined', 'Declined')], default='pending_verification', max_length=30, verbose_name='Verification Status')),
                ('verification_date', models.DateTimeField(blank=True, null=True, verbose_name='Verification Date')),
                ('decline_reason', models.TextField(blank=True, help_text='Reason for declining candidate (when status is declined)', verbose_name='Decline Reason')),
                ('payment_cleared', models.BooleanField(default=False, help_text="TRUE if this candidate's fees have been cleared/paid. Proceed to decision and process audit trail", verbose_name='Payment Cleared')),
                ('payment_cleared_date', models.DateField(blank=True, null=True, verbose_name='Payment Cleared Date')),
                ('payment_amount_cleared', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Payment Amount Cleared')),
                ('payment_center_series_ref', models.CharField(blank=True, help_text='Reference to center series payment transaction (if center_series_id)', max_length=100, verbose_name='Payment Center Series Reference')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='assessment_centers.assessmentcenter', verbose_name='Assessment Center')),
                ('assessment_center_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='assessment_centers.centerbranch', verbose_name='Assessment Center Branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_candidates', to='users.staff', verbose_name='Created By')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='configurations.district', verbose_name='Home District')),
                ('nature_of_disability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='configurations.natureofdisability', verbose_name='Nature of Disability')),
                ('occupation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='occupations.occupation', verbose_name='Occupation')),
                ('payment_cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_cleared_candidates', to='users.staff', verbose_name='Payment Cleared By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_candidates', to='users.staff', verbose_name='Updated By')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_candidates', to='users.staff', verbose_name='Verified By')),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='configurations.village', verbose_name='Village')),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['registration_number'], name='candidates__registr_287cc0_idx'), models.Index(fields=['registration_category'], name='candidates__registr_30ffaa_idx'), models.Index(fields=['status'], name='candidates__status_0f124f_idx'), models.Index(fields=['verification_status'], name='candidates__verific_118207_idx'), models.Index(fields=['assessment_center'], name='candidates__assessm_a4b9f6_idx'), models.Index(fields=['occupation'], name='candidates__occupat_be90f0_idx'), models.Index(fields=['entry_year', 'intake'], name='candidates__entry_y_a6bd9a_idx')],
            },
        ),
    ]
