# Generated by Django 5.0.14 on 2025-12-24 21:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_series', '0001_initial'),
        ('candidates', '0002_alter_candidate_nationality'),
        ('occupations', '0004_occupationpaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Amount (UGX)')),
                ('is_active', models.BooleanField(default=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='assessment_series.assessmentseries')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='candidates.candidate')),
                ('occupation_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='occupations.occupationlevel')),
            ],
            options={
                'verbose_name': 'Candidate Enrollment',
                'verbose_name_plural': 'Candidate Enrollments',
                'ordering': ['-enrolled_at'],
                'unique_together': {('candidate', 'assessment_series', 'occupation_level')},
            },
        ),
        migrations.CreateModel(
            name='EnrollmentModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='candidates.candidateenrollment')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='occupations.occupationmodule')),
            ],
            options={
                'verbose_name': 'Enrollment Module',
                'verbose_name_plural': 'Enrollment Modules',
                'ordering': ['module__module_code'],
                'unique_together': {('enrollment', 'module')},
            },
        ),
        migrations.CreateModel(
            name='EnrollmentPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='candidates.candidateenrollment')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='occupations.occupationpaper')),
            ],
            options={
                'verbose_name': 'Enrollment Paper',
                'verbose_name_plural': 'Enrollment Papers',
                'ordering': ['paper__paper_code'],
                'unique_together': {('enrollment', 'paper')},
            },
        ),
    ]
