# Generated by Django 5.0.14 on 2025-12-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidateenrollment_enrollmentmodule_enrollmentpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_submitted',
            field=models.BooleanField(default=False, help_text='Whether the candidate registration has been submitted', verbose_name='Is Submitted'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Unique registration number generated when candidate is submitted', max_length=50, null=True, unique=True, verbose_name='Registration Number'),
        ),
    ]
