# Generated by Django 5.0.14 on 2025-12-24 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_candidate_is_submitted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='passport_photo_with_regno',
        ),
    ]
