# Generated by Django 5.0.14 on 2025-12-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_remove_candidate_passport_photo_with_regno'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='payment_code',
            field=models.CharField(blank=True, help_text='Unique payment code in format: IUV00225000001', max_length=50, null=True, unique=True, verbose_name='Payment Code'),
        ),
    ]
