# Generated by Django 5.0.14 on 2025-12-26 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_candidate_payment_code'),
        ('occupations', '0006_occupationpaper_module'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidateenrollment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='candidateenrollment',
            name='occupation_level',
            field=models.ForeignKey(blank=True, help_text="Level for formal/modular candidates. Null for Worker's PAS (they select papers from any level)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='occupations.occupationlevel'),
        ),
    ]
