# Generated by Django 5.0.14 on 2026-01-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_alter_candidateenrollment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='intake',
            field=models.CharField(
                choices=[
                    ('M', 'March'),
                    ('J', 'June'),
                    ('S', 'September'),
                    ('D', 'December'),
                    ('A', 'August'),
                ],
                max_length=1,
                verbose_name='Assessment Intake',
            ),
        ),
    ]
