# Generated by Django 5.0.14 on 2026-01-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_alter_candidate_intake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='nationality',
            field=models.CharField(default='Uganda', max_length=100, verbose_name='Nationality'),
        ),
    ]
