# Generated by Django 5.0.14 on 2026-02-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0012_backfill_candidate_activity'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='candidateactivity',
            new_name='candidates__candida_906e21_idx',
            old_name='candidates_candida_2ec30e_idx',
        ),
        migrations.RenameIndex(
            model_name='candidateactivity',
            new_name='candidates__action_da4993_idx',
            old_name='candidates_candida_7a18b5_idx',
        ),
        migrations.AddField(
            model_name='candidate',
            name='transcript_serial_number',
            field=models.CharField(blank=True, help_text='Unique transcript serial number (TR SNo)', max_length=50, null=True, unique=True, verbose_name='Transcript Serial Number'),
        ),
    ]
