# Generated by Django 5.0.14 on 2026-02-07 08:42

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0013_rename_candidates_candida_2ec30e_idx_candidates__candida_906e21_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='candidate_country',
            field=django_countries.fields.CountryField(blank=True, default='UG', help_text='Country of nationality', max_length=2, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='nationality',
            field=models.CharField(default='Uganda', help_text='Legacy field - will be migrated to candidate_country', max_length=100, verbose_name='Nationality (Legacy)'),
        ),
    ]
