# Generated by Django 5.0.14 on 2026-02-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0014_candidate_candidate_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='transcript_collected',
            field=models.BooleanField(default=False, help_text='Whether the printed transcript has been collected', verbose_name='Transcript Collected'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='transcript_collection_date',
            field=models.DateField(blank=True, help_text='Date when the transcript was collected', null=True, verbose_name='Collection Date'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='transcript_collector_name',
            field=models.CharField(blank=True, help_text='Name of the person who collected the transcript', max_length=200, null=True, verbose_name='Collector Name'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='transcript_collector_phone',
            field=models.CharField(blank=True, help_text='Phone number of the person who collected the transcript', max_length=20, null=True, verbose_name='Collector Phone'),
        ),
    ]
