# Generated by Django 5.0.14 on 2026-04-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0015_add_transcript_collection_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='verification_status',
            field=models.CharField(choices=[('pending_verification', 'Pending Verification'), ('verified', 'Verified'), ('declined', 'Declined'), ('editable', 'Editable')], default='pending_verification', max_length=30, verbose_name='Verification Status'),
        ),
    ]
