# Generated by Django 5.0.14 on 2025-12-18 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_number', models.CharField(help_text='Enter a unique center number (e.g., UVT001)', max_length=50, unique=True)),
                ('center_name', models.CharField(help_text='Enter the full name of the assessment center', max_length=200)),
                ('assessment_category', models.CharField(choices=[('VTI', 'Vocational Training Institute'), ('TTI', 'Technical Training Institute'), ('workplace', 'Workplace')], max_length=20)),
                ('contact_1', models.CharField(blank=True, help_text='Phone number or contact information for the center (optional)', max_length=15, verbose_name='Contact 1')),
                ('contact_2', models.CharField(blank=True, help_text='Secondary contact (optional)', max_length=15, verbose_name='Contact 2')),
                ('has_branches', models.BooleanField(default=False, help_text='Check if this center will have multiple branches in different locations', verbose_name='Has Branches?')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_centers', to='configurations.district')),
                ('village', models.ForeignKey(blank=True, help_text='You can add the village later during editing if needed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_centers', to='configurations.village')),
            ],
            options={
                'verbose_name': 'Assessment Center',
                'verbose_name_plural': 'Assessment Centers',
                'ordering': ['center_number'],
            },
        ),
        migrations.CreateModel(
            name='CenterBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(help_text='Enter a unique branch code (e.g., UVT001-B1)', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='assessment_centers.assessmentcenter')),
                ('district', models.ForeignKey(help_text='Select the district where this branch is located', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='center_branches', to='configurations.district')),
                ('village', models.ForeignKey(blank=True, help_text='Select the village where this branch is located', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='center_branches', to='configurations.village')),
            ],
            options={
                'verbose_name': 'Center Branch',
                'verbose_name_plural': 'Center Branches',
                'ordering': ['branch_code'],
            },
        ),
        migrations.AddIndex(
            model_name='assessmentcenter',
            index=models.Index(fields=['center_number'], name='assessment__center__2c3a3f_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentcenter',
            index=models.Index(fields=['assessment_category'], name='assessment__assessm_b32900_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentcenter',
            index=models.Index(fields=['district'], name='assessment__distric_155882_idx'),
        ),
        migrations.AddIndex(
            model_name='centerbranch',
            index=models.Index(fields=['assessment_center'], name='assessment__assessm_fa1c4c_idx'),
        ),
        migrations.AddIndex(
            model_name='centerbranch',
            index=models.Index(fields=['branch_code'], name='assessment__branch__944716_idx'),
        ),
    ]
