# Generated by Django 5.0.14 on 2026-02-19 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_centers', '0001_initial'),
        ('configurations', '0005_centerrepresentative'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterRepresentativePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('nin', models.CharField(blank=True, max_length=50, verbose_name='NIN')),
                ('country', models.CharField(blank=True, default='Uganda', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representative_persons', to='assessment_centers.assessmentcenter')),
                ('designation', models.ForeignKey(help_text='Designation/role at the center', on_delete=django.db.models.deletion.PROTECT, related_name='persons', to='configurations.centerrepresentative')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='center_representative_persons', to='configurations.district')),
            ],
            options={
                'verbose_name': 'Center Representative Person',
                'verbose_name_plural': 'Center Representative Persons',
                'ordering': ['assessment_center', 'name'],
            },
        ),
    ]
