# Generated by Django 5.0.14 on 2026-04-30 09:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment_series', '0005_add_surcharge_fields'),
        ('candidates', '0016_alter_candidate_verification_status'),
        ('occupations', '0012_occupation_wp_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkersPasBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveIntegerField(db_index=True, help_text='Global zero-padded sequence number used in the book number.', unique=True)),
                ('book_number', models.CharField(db_index=True, help_text='Full formatted book number, e.g. WP/BLD/00000001.', max_length=64, unique=True)),
                ('full_label', models.CharField(help_text="Display label as printed on the cover, e.g. 'UVTAB: WP/BLD/00000001'.", max_length=80)),
                ('pdf_file', models.FileField(blank=True, help_text='Generated PDF for this booklet.', null=True, upload_to='workers_pas/books/')),
                ('issued_date', models.DateField(default=django.utils.timezone.now)),
                ('reprint_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workers_pas_books', to='assessment_series.assessmentseries')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workers_pas_books', to='candidates.candidate')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers_pas_books_generated', to=settings.AUTH_USER_MODEL)),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workers_pas_books', to='occupations.occupation')),
            ],
            options={
                'verbose_name': "Worker's PAS Book",
                'verbose_name_plural': "Worker's PAS Books",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['candidate', 'occupation'], name='workers_pas_candida_891903_idx'), models.Index(fields=['assessment_series'], name='workers_pas_assessm_d90945_idx'), models.Index(fields=['issued_date'], name='workers_pas_issued__9c517d_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='workerspasbook',
            constraint=models.UniqueConstraint(fields=('candidate', 'occupation', 'assessment_series'), name='uniq_wp_book_candidate_occ_series'),
        ),
    ]
