# Generated by Django 5.0.14 on 2026-05-04 10:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_series', '0005_add_surcharge_fields'),
        ('candidates', '0016_alter_candidate_verification_status'),
        ('occupations', '0013_occupation_wp_occ_code'),
        ('workers_pas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerspasbook',
            name='book_number',
            field=models.CharField(db_index=True, help_text='Full formatted book number, e.g. WP/BLD/26000001.', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='workerspasbook',
            name='full_label',
            field=models.CharField(help_text="Display label as printed on the cover, e.g. 'UVTAB: WP/BLD/26000001'.", max_length=80),
        ),
        migrations.AlterField(
            model_name='workerspasbook',
            name='sequence_number',
            field=models.PositiveIntegerField(db_index=True, help_text='Per-occupation zero-padded sequence number used in the book number. Restarts at 1 for each occupation.'),
        ),
        migrations.AddConstraint(
            model_name='workerspasbook',
            constraint=models.UniqueConstraint(fields=('occupation', 'sequence_number'), name='uniq_wp_book_occ_sequence'),
        ),
    ]
