# Generated by Django 5.0.14 on 2025-12-18 13:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occ_code', models.CharField(max_length=50, unique=True, verbose_name='Occupation Code')),
                ('occ_name', models.CharField(max_length=200, verbose_name='Occupation Name')),
                ('occ_category', models.CharField(choices=[('formal', 'Formal'), ('workers_pas', "Worker's PAS")], max_length=20, verbose_name='Occupation Category')),
                ('sector', models.CharField(blank=True, help_text='Industry sector the occupation belongs to', max_length=200)),
                ('has_modular', models.BooleanField(default=False, help_text='Tick if this occupation allows Modular registration (Level 1 only)', verbose_name='Has Modular?')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Occupation',
                'verbose_name_plural': 'Occupations',
                'ordering': ['occ_code'],
                'indexes': [models.Index(fields=['occ_code'], name='occupations_occ_cod_96c960_idx'), models.Index(fields=['occ_category'], name='occupations_occ_cat_5f7b04_idx')],
            },
        ),
        migrations.CreateModel(
            name='OccupationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(help_text='Enter level name (e.g., Level 1, Level 2, etc.)', max_length=100)),
                ('structure_type', models.CharField(choices=[('modules', 'Modules'), ('papers', 'Papers')], default='modules', help_text='Does this level contain modules or papers?', max_length=20)),
                ('formal_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fee for Formal registration (varies by level)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Formal Fee (UGX)')),
                ('workers_pas_base_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Fee for Worker's PAS registration (Flat rate across levels)", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name="Worker's PAS Base Fee (UGX)")),
                ('workers_pas_per_module_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Fee per module for Worker's PAS registration (multiplied by modules enrolled)", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name="Worker's PAS Per-Module Fee (UGX)")),
                ('modular_fee_single_module', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fee for Modular registration with 1 module', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Modular Fee - Single Module (UGX)')),
                ('modular_fee_double_module', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fee for Modular registration with 2 modules', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Modular Fee - Double Module (UGX)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='occupations.occupation')),
            ],
            options={
                'verbose_name': 'Occupation Level',
                'verbose_name_plural': 'Occupation Levels',
                'ordering': ['occupation', 'level_name'],
                'indexes': [models.Index(fields=['occupation'], name='occupations_occupat_7c9e6b_idx')],
                'unique_together': {('occupation', 'level_name')},
            },
        ),
    ]
