# Generated by Django 5.0.14 on 2025-12-18 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Sector Name')),
                ('description', models.TextField(blank=True, help_text='Provide a brief description of this sector (optional)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='occupation',
            name='sector',
            field=models.ForeignKey(blank=True, help_text='Industry sector the occupation belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupations', to='occupations.sector'),
        ),
    ]
