# Generated by Django 5.0.14 on 2025-12-18 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupations', '0002_sector_alter_occupation_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccupationModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(max_length=50, unique=True, verbose_name='Module Code')),
                ('module_name', models.CharField(max_length=200, verbose_name='Module Name')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(help_text='Select the level for this module', on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='occupations.occupationlevel')),
                ('occupation', models.ForeignKey(help_text='Select the occupation this module belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='occupations.occupation')),
            ],
            options={
                'verbose_name': 'Occupation Module',
                'verbose_name_plural': 'Occupation Modules',
                'ordering': ['occupation', 'level', 'module_code'],
                'indexes': [models.Index(fields=['occupation'], name='occupations_occupat_4f153f_idx'), models.Index(fields=['level'], name='occupations_level_i_a8b2b9_idx'), models.Index(fields=['module_code'], name='occupations_module__d7bb19_idx')],
                'unique_together': {('occupation', 'module_code')},
            },
        ),
    ]
