# Generated by Django 5.0.14 on 2025-12-18 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupations', '0003_occupationmodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccupationPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_code', models.CharField(max_length=50, unique=True, verbose_name='Paper Code')),
                ('paper_name', models.CharField(max_length=200, verbose_name='Paper Name')),
                ('paper_type', models.CharField(choices=[('theory', 'Theory'), ('practical', 'Practical')], help_text='Select whether this is a Theory or Practical paper', max_length=20, verbose_name='Paper Type')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(help_text='Select the level for this paper', on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='occupations.occupationlevel')),
                ('occupation', models.ForeignKey(help_text='Select the occupation this paper belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='occupations.occupation')),
            ],
            options={
                'verbose_name': 'Occupation Paper',
                'verbose_name_plural': 'Occupation Papers',
                'ordering': ['occupation', 'level', 'paper_code'],
                'indexes': [models.Index(fields=['occupation'], name='occupations_occupat_967918_idx'), models.Index(fields=['level'], name='occupations_level_i_782a11_idx'), models.Index(fields=['paper_code'], name='occupations_paper_c_138333_idx'), models.Index(fields=['paper_type'], name='occupations_paper_t_3575f5_idx')],
                'unique_together': {('occupation', 'paper_code')},
            },
        ),
    ]
