# Generated by Django 5.0.14 on 2025-12-25 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupations', '0004_occupationpaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleLWA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lwa_name', models.CharField(max_length=200, verbose_name='LWA Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(help_text='Select the module this LWA belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='lwas', to='occupations.occupationmodule')),
            ],
            options={
                'verbose_name': 'Module LWA',
                'verbose_name_plural': 'Module LWAs',
                'ordering': ['module', 'lwa_name'],
                'indexes': [models.Index(fields=['module'], name='occupations_module__0258b6_idx')],
            },
        ),
    ]
