# Generated by Django 5.0.14 on 2025-12-25 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupations', '0005_modulelwa'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupationpaper',
            name='module',
            field=models.ForeignKey(blank=True, help_text="Select the module this paper belongs to (for Worker's PAS only)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='occupations.occupationmodule'),
        ),
    ]
