# Generated by Django 5.0.14 on 2026-02-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupations', '0006_occupationpaper_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupation',
            name='award',
            field=models.CharField(blank=True, help_text='Award/Certificate title for this occupation (used on transcripts)', max_length=200, null=True, verbose_name='Award'),
        ),
    ]
