# Generated by Django 5.0.14 on 2026-02-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupations', '0007_occupation_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupation',
            name='award_modular',
            field=models.CharField(blank=True, help_text='Award/Certificate title for modular candidates (only if Has Modular is enabled)', max_length=200, null=True, verbose_name='Award (Modular)'),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='award',
            field=models.CharField(blank=True, help_text='Award/Certificate title for full occupation candidates (used on transcripts)', max_length=200, null=True, verbose_name='Award (Full Occupation)'),
        ),
    ]
