# Generated by Django 5.0.14 on 2026-02-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupations', '0008_occupation_award_modular_alter_occupation_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupation',
            name='contact_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Total contact hours for this occupation', null=True, verbose_name='Contact Hours'),
        ),
    ]
