# Generated by Django 5.0.14 on 2026-02-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupations', '0009_occupation_contact_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupationmodule',
            name='credit_units',
            field=models.PositiveIntegerField(default=0, help_text='Number of credit units for this module', verbose_name='Credit Units (CU)'),
        ),
        migrations.AddField(
            model_name='occupationpaper',
            name='credit_units',
            field=models.PositiveIntegerField(default=0, help_text='Number of credit units for this paper', verbose_name='Credit Units (CU)'),
        ),
    ]
