# Generated by Django 5.0.14 on 2026-02-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupations', '0010_occupationmodule_credit_units_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occupation',
            name='award',
        ),
        migrations.RemoveField(
            model_name='occupation',
            name='contact_hours',
        ),
        migrations.AddField(
            model_name='occupationlevel',
            name='award',
            field=models.CharField(blank=True, help_text='Award/Certificate title for this level (used on transcripts)', max_length=200, null=True, verbose_name='Award'),
        ),
        migrations.AddField(
            model_name='occupationlevel',
            name='contact_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Total contact hours for this level', null=True, verbose_name='Contact Hours'),
        ),
    ]
