# Generated by Django 5.0.14 on 2026-04-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupations', '0011_remove_occupation_award_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupation',
            name='wp_code',
            field=models.CharField(blank=True, help_text="Short code used in Worker's PAS booklet numbering, e.g. BLD for Builder. Required when category is Worker's PAS.", max_length=10, null=True, verbose_name="Worker's PAS Code"),
        ),
        migrations.AddField(
            model_name='occupationlevel',
            name='competence_description',
            field=models.TextField(blank=True, help_text="Description of competencies for this level shown on page 6 of the Worker's PAS booklet (the section intro).", null=True, verbose_name="Competence Description (Worker's PAS)"),
        ),
        migrations.AddField(
            model_name='occupationlevel',
            name='level_description',
            field=models.TextField(blank=True, help_text="Description for this level shown on page 4 of the Worker's PAS booklet.", null=True, verbose_name="Level Description (Worker's PAS)"),
        ),
        migrations.AddField(
            model_name='occupationmodule',
            name='wp_competence_items',
            field=models.TextField(blank=True, help_text='Bullet list of skill items for the test area page. Enter one item per line.', null=True, verbose_name="Competence Items (Worker's PAS)"),
        ),
        migrations.AddField(
            model_name='occupationmodule',
            name='wp_description',
            field=models.TextField(blank=True, help_text="Intro paragraph shown on the test area detail page in the Worker's PAS booklet, e.g. 'The Worker has acquired adequate knowledge and skills to construct Foundations/Substructures e.g.;'", null=True, verbose_name="Test Area Description (Worker's PAS)"),
        ),
    ]
