# Generated by Django 5.0.14 on 2026-05-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupations', '0012_occupation_wp_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupation',
            name='wp_occ_code',
            field=models.PositiveIntegerField(blank=True, help_text="Numeric occupation code used as the prefix of the booklet sequence, e.g. 26 for Builder -> WP/BLD/26000001. The 6-digit sequence restarts per occupation. Required for Worker's PAS occupations.", null=True, unique=True, verbose_name="Worker's PAS Occupation Number"),
        ),
    ]
