# Generated by Django 5.0.14 on 2026-05-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupations', '0013_occupation_wp_occ_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupation',
            name='cover_color',
            field=models.CharField(default='#7d7d7d', help_text="Hex colour (e.g. #7d7d7d) used for the front and back covers of this occupation's Worker's PAS booklet.", max_length=7, verbose_name='Booklet Cover Colour'),
        ),
    ]
