# Generated by Django 5.0.14 on 2026-06-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupations', '0015_merge_20260506_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupation',
            name='wp_occ_name',
            field=models.CharField(blank=True, help_text="Name used on the Worker's PAS booklet (e.g. 'Builder' instead of 'Builder Wp'). Falls back to Occupation Name if blank.", max_length=200, null=True, verbose_name="Worker's PAS Book Name"),
        ),
        migrations.AddField(
            model_name='occupationlevel',
            name='wp_level_name',
            field=models.CharField(blank=True, help_text="Name shown on the booklet for this level (e.g. 'Level 4'). Falls back to Level Name if blank. Also controls numbering on the cover and section pages.", max_length=100, null=True, verbose_name="Worker's PAS Level Name"),
        ),
    ]
