# Generated by Django 5.0.14 on 2026-01-03 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='semester',
        ),
    ]
