# Generated by Django 5.0.14 on 2026-01-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_remove_complaint_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
