# Generated by Django 5.0.14 on 2025-12-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a descriptive name for this assessment series (e.g., "March 2024 Assessment")', max_length=200, unique=True, verbose_name='Assessment Series Name')),
                ('start_date', models.DateField(help_text='Assessment period begins', verbose_name='Start Date')),
                ('end_date', models.DateField(help_text='Assessment period ends', verbose_name='End Date')),
                ('date_of_release', models.DateField(help_text='Date when results will be released', verbose_name='Results Release Date')),
                ('is_current', models.BooleanField(default=False, help_text='Mark this as the currently active assessment series. Only one series can be current at a time.', verbose_name='Set as Current Assessment Series')),
                ('results_released', models.BooleanField(default=False, help_text='Toggle to release results to candidates and assessment centers', verbose_name='Results Released')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assessment Series',
                'verbose_name_plural': 'Assessment Series',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['start_date'], name='assessment__start_d_e9bb2b_idx'), models.Index(fields=['end_date'], name='assessment__end_dat_1c664c_idx'), models.Index(fields=['is_current'], name='assessment__is_curr_5a8d8c_idx'), models.Index(fields=['results_released'], name='assessment__results_09239f_idx')],
            },
        ),
    ]
