# Generated by Django 5.0.14 on 2026-01-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentseries',
            name='dont_charge',
            field=models.BooleanField(default=False, help_text='If enabled, candidates enrolled in this series will not be charged any fees', verbose_name="Don't Charge"),
        ),
    ]
