# Generated by Django 5.0.14 on 2026-02-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_series', '0002_assessmentseries_dont_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentseries',
            name='completion_year',
            field=models.CharField(blank=True, help_text='Completion year/period (e.g., "November, 2025")', max_length=100, null=True, verbose_name='Completion Year'),
        ),
    ]
