# Generated by Django 5.0.14 on 2026-02-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_series', '0003_assessmentseries_completion_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentseries',
            name='quarter',
            field=models.CharField(blank=True, choices=[('Q1', 'Q1 (July - September)'), ('Q2', 'Q2 (October - December)'), ('Q3', 'Q3 (January - March)'), ('Q4', 'Q4 (April - June)')], help_text='Uganda fiscal year quarter: Q1(Jul-Sep), Q2(Oct-Dec), Q3(Jan-Mar), Q4(Apr-Jun)', max_length=2, null=True, verbose_name='Fiscal Quarter'),
        ),
    ]
