# Generated by Django 5.0.14 on 2026-04-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_series', '0004_assessmentseries_quarter'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentseries',
            name='surcharge_100',
            field=models.BooleanField(default=False, help_text='Apply 100% surcharge to enrollment fees (e.g., 70,000 becomes 140,000)', verbose_name='100% Surcharge'),
        ),
        migrations.AddField(
            model_name='assessmentseries',
            name='surcharge_50',
            field=models.BooleanField(default=False, help_text='Apply 50% surcharge to enrollment fees (e.g., 70,000 becomes 105,000)', verbose_name='50% Surcharge'),
        ),
    ]
