# Generated by Django 5.0.14 on 2025-12-18 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemConfiguration',
        ),
    ]
