# Generated by Django 5.0.14 on 2025-12-24 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0002_delete_systemconfiguration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailTemplate',
        ),
    ]
