# Generated by Django 5.0.14 on 2026-02-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0003_delete_emailtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReprintReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('requires_duplicate_watermark', models.BooleanField(default=False, help_text="If checked, reprinted transcripts with this reason will have a 'DUPLICATE' watermark")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reprint Reason',
                'verbose_name_plural': 'Reprint Reasons',
                'ordering': ['name'],
            },
        ),
    ]
