# Generated by Django 5.0.14 on 2025-12-26 22:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment_centers', '0001_initial'),
        ('assessment_series', '0001_initial'),
        ('candidates', '0007_alter_candidateenrollment_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_code', models.CharField(max_length=100, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('not_paid', 'Not Paid'), ('pending_approval', 'Pending Approval'), ('successful', 'Successful'), ('failed', 'Failed')], default='not_paid', max_length=20)),
                ('attempt_status', models.CharField(choices=[('no_attempt', 'No Attempt'), ('failed', 'Failed'), ('pending_approval', 'Pending Approval'), ('successful', 'Successful')], default='no_attempt', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_fees', to='assessment_series.assessmentseries')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='candidates.candidate')),
            ],
            options={
                'verbose_name': 'Candidate Fee',
                'verbose_name_plural': 'Candidate Fees',
                'db_table': 'candidate_fees',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CenterFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_candidates', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='assessment_centers.assessmentcenter')),
                ('assessment_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_fees', to='assessment_series.assessmentseries')),
            ],
            options={
                'verbose_name': 'Center Fee',
                'verbose_name_plural': 'Center Fees',
                'db_table': 'center_fees',
                'ordering': ['-created_at'],
                'unique_together': {('assessment_series', 'assessment_center')},
            },
        ),
    ]
