# Generated by Django 5.0.14 on 2026-02-23 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatefee',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_fees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidatefee',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatefee',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_fees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidatefee',
            name='marked_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatefee',
            name='payment_reference',
            field=models.CharField(blank=True, choices=[('bulk_payment', 'Bulk Payment'), ('via_schoolpay', 'Via SchoolPay')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='candidatefee',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('marked', 'Marked as Paid'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
    ]
