# Generated by Django 5.0.14 on 2026-02-19 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment_centers', '0001_initial'),
        ('candidates', '0015_add_transcript_collection_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(choices=[('head_of_center', 'Head of Center'), ('academic_registrar', 'Academic Registrar'), ('director_of_studies', 'Director of Studies'), ('candidate', 'Candidate'), ('other_person', 'Other Person')], max_length=30, verbose_name='Designation')),
                ('nin', models.CharField(help_text='National Identification Number of the collector', max_length=50, verbose_name='NIN')),
                ('collector_name', models.CharField(max_length=200, verbose_name='Collector Name')),
                ('collector_phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(help_text='Email address to receive the collection receipt', max_length=254, verbose_name='Email')),
                ('collection_date', models.DateField(verbose_name='Date of Collection')),
                ('signature_data', models.TextField(blank=True, help_text='Base64 encoded signature image from signature pad', null=True, verbose_name='Signature Data')),
                ('supporting_document', models.FileField(blank=True, help_text='Required for Candidate and Other Person designations', null=True, upload_to='transcript_collections/documents/', verbose_name='Supporting Document')),
                ('candidate_count', models.PositiveIntegerField(default=0, verbose_name='Number of Candidates')),
                ('receipt_number', models.CharField(help_text='Auto-generated collection receipt number', max_length=50, unique=True, verbose_name='Receipt Number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transcript_collections', to='assessment_centers.assessmentcenter', verbose_name='Exam Center')),
                ('candidates', models.ManyToManyField(related_name='transcript_collections', to='candidates.candidate', verbose_name='Candidates')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcript_collections_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transcript Collection',
                'verbose_name_plural': 'Transcript Collections',
                'ordering': ['-created_at'],
            },
        ),
    ]
