# Generated by Django 5.0.14 on 2026-02-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptcollection',
            name='designation',
            field=models.CharField(help_text='Config designation name (e.g. Head of Center) or special: candidate, other_person', max_length=100, verbose_name='Designation'),
        ),
    ]
