# Generated by Django 5.0.14 on 2026-01-03 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_centers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('staff', 'Staff'), ('support_staff', 'Support Staff'), ('center_representative', 'Center Representative'), ('candidate', 'Candidate')], default='candidate', max_length=25),
        ),
        migrations.CreateModel(
            name='CenterRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200, verbose_name='Full Name')),
                ('contact', models.CharField(max_length=15, verbose_name='Contact Number')),
                ('email', models.EmailField(editable=False, max_length=254, unique=True)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representatives', to='assessment_centers.assessmentcenter')),
                ('assessment_center_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representatives', to='assessment_centers.centerbranch', verbose_name='Assessment Center Branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_center_reps', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='center_rep_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Center Representative',
                'verbose_name_plural': 'Center Representatives',
                'ordering': ['-created_at'],
            },
        ),
    ]
